### ISSUE TITLE
Feed back from users with the

### ISSUE THREAD

**Issue by alwatud** [MaxBo/REPAiR-Web#425]
This is a list of things I noted down while usning the GDSE during the AMS PULL.

- check the projection of actors, people say, but the bakery is in the other street, seems something is off.
- all check boxes are to small to tick with fingers please enlarge them
- there seems to be something wrong with thousand separators ans commas.

overall the GDSE alrady functioned very nicely as research tool.

**Comment by rusne** [comment]
@ChrFr I will check the projections, can you take care of the other two points?

For the thousand separator - could it just be a space instead of a comma? so five thousands would look like 5 000 instead of 5,000. Since different countries use different standards, its difficult to understand whether the coma is for the thousands or for the decimals. All amounts are integers, do decimal separator is not an issue anyway.

**Comment by ChrFr** [comment]
the numbers are formatted in relation to the country setting (top right). maybe english was set?
